name: CI Pipeline for Fraud Detection Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest nbconvert

    - name: Run linting with flake8
      run: |
        flake8 scripts/ tests/ --max-line-length=120 --ignore=E203,W503

    - name: Run unit tests with pytest
      run: |
        pytest tests/ -v

    - name: Validate Jupyter notebook execution
      run: |
        jupyter nbconvert --to notebook --execute --inplace notebooks/eda-1.ipynb